# Generated by Django 4.1.7 on 2023-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientinstallations', '0002_applicationinstance_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='product',
            field=models.CharField(choices=[('ECOI', 'ECOI'), ('CCR', 'CCR'), ('IAR', 'IAR'), ('Mobile', 'Mobile'), ('User Management', 'User Management')], max_length=50),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internalipv4', models.CharField(max_length=100)),
                ('externalipv4', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('WebServer', 'WebServer'), ('Database', 'Database'), ('Services', 'Services'), ('DC', 'DC'), ('FTP', 'FTP'), ('SMTP', 'SMTP'), ('WebProxy', 'WebProxy'), ('Other', 'Other')], max_length=100)),
                ('trustlevel', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ServerGroup', models.ManyToManyField(to='clientinstallations.servergroup')),
            ],
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, to='clientinstallations.server'),
        ),
    ]
