# Generated by Django 4.1.7 on 2023-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientinstallations', '0005_customisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgradedate', models.DateTimeField()),
                ('versionfrom', models.CharField(max_length=50)),
                ('versionto', models.CharField(max_length=50)),
                ('engineer', models.CharField(max_length=100)),
                ('ticketlink', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Customisation',
        ),
    ]
