# Generated by Django 4.1.7 on 2023-05-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientinstallations', '0006_upgrade_delete_customisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='clientinstallations.applicationinstance'),
        ),
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('adolink', models.CharField(max_length=100)),
                ('ticketlink', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='clientinstallations.applicationinstance')),
            ],
        ),
    ]
